### PR TITLE
Automatically get latest Concrete5

### PR DESCRIPTION
**Pull request by tbjers**
Automatically derive latest version of Concrete5 and download that instead of arbitrarily selected version. Moved zip installation to top of file.

### CODE REVIEW

**Comment by a3020** [comment]
@tbjers thanks for the PR. I've talked with the core team and they don't have a direct link to the latest stable yet, unfortunately. So yes, we have to retrieve it somehow from the download page.

Regarding `head` and `cut`, I think we can do that right in the grep command, don't you think?
`curl -s http://www.concrete5.org/download | grep -o -m 1 'www.concrete5.org/download_file/-/view/[0-9]*'`

**Comment by a3020** [comment]
@tbjers I just hear from @aembler and there now is a direct link available: http://concrete5.org/latest.zip

**Comment by tbjers** [comment]
Perfect, I'll amend my PR with this!

**Comment by a3020** [comment]
@tbjers Thanks!

**Pull request merged**
